[tasks.wit-deps-fetch]
command = "wash"
args = ["wit", "deps"]

[tasks.build]
command = "cargo"
args = ["leptos", "build"]
dependencies = ["wit-deps-fetch"]

[tasks.build-prod]
command = "cargo"
args = ["leptos", "build", "--release"]
dependencies = ["wit-deps-fetch"]

[tasks.wash-build]
command = "wash"
args = ["claims", "sign", "./{{component_outdir}}/wasm32-wasip2/debug/{{project-name}}.wasm", "-d", "./{{component_outdir}}/wasm32-wasip2/debug/{{project-name}}_s.wasm"]

[tasks.wash-build-prod]
command = "wash"
args = ["claims", "sign", "./{{component_outdir}}/wasm32-wasip2/wasm-release/{{project-name}}.wasm", "-d", "./{{component_outdir}}/wasm32-wasip2/wasm-release/{{project-name}}_s.wasm"]
